### PR TITLE
[WIP] Panel's Shenanigans

### PR DESCRIPTION
**Pull request by ZeGentzy**
-- Bumps the version from C++11 to C++14 
-- Adds -Wpedantic and -Werror
-- Addings split and padding panels
-- Replaces options menu with quick demo of those two panels

This branch will eventually rewrite the options menu to use the new
panels system Im working on.

Signed-off-by: Hal Gentz <zegentzy@protonmail.com>

---------------------------------------------------------------------------

I'm very sorry I couldn't get started on this earlier and I know I told you I'd start working on it like a month ago but the times have been busy. Anyways, since spring break approaches, I should have more time to work on this.

### CODE REVIEW

**Comment by ZeGentzy** [comment]
I'll get on to tabs next.

**Comment by ZeGentzy** [comment]
Nothing is complete without pics: https://i.imgur.com/ZNrpYAG.png
The two red panels are the debug ones.

**Comment by Wulfe813** [comment]
> I'm very sorry I couldn't get started on this earlier

No worries, man. Just glad to see you're still with us.  I was worried that something bad might have happened to you, honestly.

**Comment by Wulfe813** [comment]
If you have the time, I'd like to talk to you over IRC at some point. I just missed you last night(I was in the midst of reinstalling my OS.)

**Pull request closed without merging**
